name: Build WebApp APK
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Convert Website to APK
        uses: shashankauli/website-to-apk-action@master
        with:
          website_url: 'https://cuba-ticket.free.nf/dashboard.php'
          app_name: 'CubaTiket'
          package_name: 'com.cubatiket.app'
